server:
  port: 9190

spring:
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://localhost:5432/aces_btc_ark_lite_channel_service_db"
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: "validate"

serverInfo:
  name: "Aces BTC-ARK Lite Channel Service"
  description: "ACES BTC to ARK Lite Channel service for transferring BTC to ARK"
  instructions: >
    After this contract is executed, any BTC sent to depositBtcAddress will be exchanged for ARK and 
    sent directly to the given recipientArkAddress less service fees.
  version: "1.0.0"
  websiteUrl: "https://arkaces.com"
  inputSchema: >
    {
      "type": "object",
      "properties": {
        "recipientArkAddress": {
          "type": "string",
          "title": "Recipient ARK Address",
          "description": "Enter recipient ARK address to transfer funds to."
        },
         "returnBtcAddress": {
            "type": "string",
            "title": "Return BTC Address",
            "description": "Enter return BTC address to send returns to."
          }
      },
      "required": [
        "recipientArkAddress"
      ]
    }
  outputSchema: >
    {
      "type": "object",
      "properties": {
        "depositBtcAddress": {
          "type": "string"
        },
        "recipientArkAddress": {
          "type": "string"
        },
        "transfers": {
          "type": "array",
          "properties": {
            "btcAmount": {
              "type": "string"
            },
            "btcToArkRate": {
              "type": "string"
            },
            "btcFlatFee": {
              "type": "string"
            },
            "btcPercentFee": {
              "type": "string"
            },
            "btcTotalFee": {
              "type": "string"
            },
            "arkSendAmount": {
              "type": "string"
            },
            "arkTransactionId": {
              "type": "string"
            },
            "createdAt": {
              "type": "string"
            }
          }
        }
      }
    }

arkNetworkConfigPath: "ark_network_config/mainnet.yml"

serviceCapacityUnit: "ARK"

serviceCapacityUpdateIntervalSec: 3600

bitcoinScanIntervalSec: 10

flatFee:
  amount: 0.0001
  unit: "BTC"

percentFee: 1

serviceArkAccount:
  address: "change-me"
  passphrase: "change-me"

serviceBitcoinAccount:
  privateKey: "change-me"

bitcoinMinConfirmations: 1

electrumNetworkConfigPath: "electrum_network_config/mainnet.yml"
