server:
  port: 9190

spring:
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://localhost:5432/aces_btc_ark_lite_channel_service_db"
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: "validate"

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false


serverInfo:
  name: "Aces BTC-ARK Lite Channel Service"
  description: "ACES BTC to ARK Lite Channel service for transferring BTC to ARK"
  instructions: >
    After this contract is executed, any BTC sent to depositBtcAddress will be exchanged for ARK and 
    sent directly to the given recipientArkAddress less service fees.
  version: "1.0.0"
  websiteUrl: "https://arkaces.com"
  inputSchema: >
    {
      "type": "object",
      "properties": {
        "recipientArkAddress": {
          "type": "string",
          "title": "Recipient ARK Address",
          "description": "Enter recipient ARK address to transfer funds to."
        },
         "returnBtcAddress": {
            "type": "string",
            "title": "Return BTC Address",
            "description": "Enter return BTC address to send returns to."
          }
      },
      "required": [
        "recipientArkAddress"
      ]
    }
  outputSchema: >
    {
      "type": "object",
      "properties": {
        "depositBtcAddress": {
          "type": "string",
          "title": "Deposit BTC Address",
          "description": "Send BTC to this address to execute contract."
        },
        "recipientArkAddress": {
          "type": "string",
          "title": "Recipient ARK Address",
          "description": "ARK will arrive at this address on contract execution."
        },
        "returnBtcAddress": {
          "type": "string",
          "title": "Return BTC Address",
          "description": "Returned BTC amounts are sent to this address."
        },
        "transfers": {
          "type": "array",
          "properties": {
            "id": {
                "type": "string",
                "title": "Transfer ID",
                "description": "Identifier for transfer"
            },
            "status": {
                "type": "string",
                 "title": "Status",
                 "description": "The status of the transfer"
            },
            "createdAt": {
              "type": "string",
              "title": "Create Date",
              "description": "The time the contract was created."
            },
            "btcTransactionId": {
              "type": "string",
              "title": "Transaction ID (BTC)",
              "description": "The transaction ID for the BTC contract fulfillment"
            },
            "btcAmount": {
              "type": "string",
              "title": "Transfer Amount (BTC)",
              "description": "The amount of BTC to transfer"
            },
            "btcToArkRate": {
              "type": "string",
              "title": "ARK/BTC Exchange Rate",
              "description": "Amount of ARK to receive per BTC"
            },
            "btcFlatFee": {
              "type": "string",
              "title": "Flat Fee (BTC)",
              "description": "Fixed fee per execution, charged in BTC"
            },
            "btcPercentFee": {
              "type": "string",
              "title": "Percentage Fee (BTC)",
              "description": "Percentage fee per execution, charged in BTC"
            },
            "btcTotalFee": {
              "type": "string",
              "title": "Total Fees (BTC)",
              "description": "The sum of flat fees and percentage fees, charged in BTC"
            },
            "arkSendAmount": {
              "type": "string",
              "title": "Receiving Amount (ARK)",
              "Description": "Total ARK to be received, net of fees"
            },
            "arkTransactionId": {
              "type": "string",
              "title": "Transaction ID (ARK)",
              "description": "The transaction ID for the ARK contract fulfillment"
            },
            "returnBtcTransactionId": {
              "type": "string",
              "title": "Transaction ID (BTC)",
              "description": "The transaction ID for the BTC contract return"
            }
          }
        }
      }
    }
  outputSchemaUrlTemplates:
    -
      property: "depositBtcAddress"
      urlTemplate: "https://live.blockcypher.com/btc/address/{value}/"
    -
      property: "recipientArkAddress"
      urlTemplate: "https://explorer.ark.io/wallets/{value}"
    -
      property: "transfers.btcTransactionId"
      urlTemplate: "https://live.blockcypher.com/btc/tx/{value}/"
    -
      property: "transfers.arkTransactionId"
      urlTemplate: "https://explorer.ark.io/transaction/{value}"
    -
      property: "transfers.returnBtcTransactionId"
      urlTemplate: "https://live.blockcypher.com/btc/tx/{value}/"


arkNetworkConfigPath: "ark_network_config/mainnet.yml"

capacityUnit: "ARK"

capacityUpdateIntervalSec: 3600

bitcoinScanIntervalSec: 10

flatFee: 0.0001
flatFeeUnit: "BTC"

percentFee: 1

serviceArkAccount:
  address: "change-me"
  passphrase: "change-me"

serviceBitcoinAccount:
  privateKey: "change-me"

bitcoinMinConfirmations: 1

electrumNetworkConfigPath: "electrum_network_config/mainnet.yml"

exchangeRate:
  fromSymbol: "BTC"
  toSymbol: "ARK"
  multiplier: 1
